### ISSUE TITLE
Define a schema for the JSON files we create

### ISSUE THREAD

**Issue by glesica** [code-for-montana/nonprofit-data#36]
The plan right now is to grab the XML or CSV files, grab what we want, then stuff it into a bunch of JSON files, probably one per module. The frontend then grabs the JSON and goes to town. So when we update the data we'll just replace some or all of the JSON files and then push them to the server to be consumed by the client.

So, we need a schema for the data we're going to store as JSON. We don't need crazy detail here, just some idea so that we can create some fixtures for the frontend development to use.

**Comment by smai-f** [comment]
@glesica can we close this one?

**Comment by glesica** [comment]
Yeah, probably. I've more or less defined this in code.
